services:
  - type: web
    name: taskmanager
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: H2_FILE_PATH
        value: /data/taskmanagerdb
      - key: H2_CONSOLE_ENABLED
        value: "false"
      - key: PORT
        value: "8080"
